app:
    SOAP:
        Token: "D468E929-A94E-4F16-A7D2-DB414EC53071"
        BaseReqURL: "http://www.hostco.ru/reguser"
        URL: "https://cas-test.hostco.ru/RegUserService/services/RegUserService"
    REST:
        ServiceURL: "http://localhost:8112"

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/archidb
        username: archi
        password: 1234
    flyway:
        url: jdbc:postgresql://localhost:5432/archidb
        user: postgres
        password: 1234

server:
    error.include-message: always

logging.level.org.springframework.ws: TRACE